name: Createas
on:
  push:
    branches:
      - master
      
env:
  name: "Android Studio sa"
  comment: "Android Studio for Windsaows"
  url: "https://fs1.1cloudfile.com/token/download/dl/kx6C/No.Plan.B.Build.14244705.rar?download_token=e48a82114d73c5842ee848dc161061ce8f6e89f832ee39dacf2bf8cb73290611"
  file_name: "android-studio-ide-201.7042882-windows.exe"
  piece_size: 2^19 = 524 288 = 512 KiB
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
